// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbcbybaprqrodlcbpikg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiY2J5YmFwcnFyb2RsY2JwaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzE3MjUsImV4cCI6MjA1ODA0NzcyNX0.xt2UqLHZ0C4puOb3VfRxbd2XjVKvP2BGjbXaB6imlpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});